# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [9]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [10]:
x = np.array(range(0,20))
y = x * 2 -1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [11]:
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘
keras.backend.clear_session()

# 2번 모델 선언
model = keras.models.Sequential()

# 3번 모델 블록 조립
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [12]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 272ms/step - loss: 1377.4673
Epoch 2/10
1/1 [==============================] - 0s 11ms/step - loss: 1376.5797
Epoch 3/10
1/1 [==============================] - 0s 8ms/step - loss: 1375.6924
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 1374.8054
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 1373.9187
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 1373.0323
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 1372.1461
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 1371.2605
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 1370.3750
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1369.4900


In [13]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [14]:
model.predict(x).reshape(-1) # 2차원 -> 1차원으로 변경

array([ 9.9989148e-03, -1.3962966e+00, -2.8025923e+00, -4.2088876e+00,
       -5.6151834e+00, -7.0214791e+00, -8.4277735e+00, -9.8340693e+00,
       -1.1240365e+01, -1.2646661e+01, -1.4052957e+01, -1.5459251e+01,
       -1.6865547e+01, -1.8271843e+01, -1.9678139e+01, -2.1084435e+01,
       -2.2490730e+01, -2.3897026e+01, -2.5303322e+01, -2.6709618e+01],
      dtype=float32)

## Now, Your turn!

In [21]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [22]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [23]:
print(x.shape, y.shape)

(20,) (20,)


In [24]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

model.compile(loss='mse', optimizer='adam')

In [25]:
model.fit(x, y, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 273ms/step - loss: 442.4095
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 441.9272
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 441.4450
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 440.9633
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 440.4818
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 440.0007
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 439.5198
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 439.0392
Epoch 9/10
1/1 [==============================] - 0s 11ms/step - loss: 438.5591
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 438.0792


In [28]:
pred_y = model.predict(x).reshape(-1)
pred_y

array([-0.00999768, -0.41657245, -0.8231472 , -1.229722  , -1.6362967 ,
       -2.0428715 , -2.4494462 , -2.856021  , -3.2625957 , -3.6691704 ,
       -4.0757456 , -4.4823203 , -4.888895  , -5.2954698 , -5.7020445 ,
       -6.108619  , -6.515194  , -6.9217687 , -7.3283434 , -7.734918  ],
      dtype=float32)

In [27]:
y

array([ 10,   7,   4,   1,  -2,  -5,  -8, -11, -14, -17, -20, -23, -26,
       -29, -32, -35, -38, -41, -44, -47])

## Quick Logistic Regression!

In [5]:
import tensorflow as tf
import tensorflow.keras as keras # Not Recommended!

import numpy as np

In [6]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [7]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', # 분포와 분포를 비교
              optimizer = 'adam',
              metrics=['accuracy'])         # CrossEntropy는 직관적이지 않아 보조지표 추가로 사용

In [8]:
# 데이터를 넣어서 학습시키자!
model.fit(x[:15], y[:15], epochs=10, verbose=1) # Threshold 적용 X

# 결과 출력해줘!
print(y[15:])
print(model.predict(x[15:]))

Epoch 1/10
1/1 [==============================] - 1s 631ms/step - loss: 5.2505 - accuracy: 0.6667
Epoch 2/10
1/1 [==============================] - 0s 13ms/step - loss: 5.2463 - accuracy: 0.6000
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 5.2420 - accuracy: 0.6000
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 5.2378 - accuracy: 0.6000
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 5.2335 - accuracy: 0.6000
Epoch 6/10
1/1 [==============================] - 0s 7ms/step - loss: 5.2293 - accuracy: 0.6000
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 5.2250 - accuracy: 0.6000
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 5.2208 - accuracy: 0.6000
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 5.2165 - accuracy: 0.6000
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 5.2123 - accuracy: 0.6000
[1 1 1 1 1]
[[4.2744892e-09]
 [1.18

## Now, Your turn!

In [29]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [30]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [31]:
keras.backend.clear_session()

model = keras.models.Sequential()

model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [38]:
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
2/2 [==============================] - 0s 6ms/step - loss: 8.5774 - accuracy: 0.4750
Epoch 2/10
2/2 [==============================] - 0s 7ms/step - loss: 8.5476 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 5ms/step - loss: 8.5172 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 5ms/step - loss: 8.4874 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 5ms/step - loss: 8.4577 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 8ms/step - loss: 8.4256 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 6ms/step - loss: 8.3991 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 6ms/step - loss: 8.3646 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 4ms/step - loss: 8.3355 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 3ms/step - loss: 8.3052 - accuracy: 0.4750


In [36]:
pred_y = model.predict(x[:10]).reshape(-1)
pred_y

array([0.5052953 , 0.3639813 , 0.24279198, 0.15229148, 0.09145078,
       0.05338538, 0.03063011, 0.01739597, 0.00982189, 0.00552696],
      dtype=float32)

In [40]:
pred_y = np.where(pred_y >= 0.5, 1, 0) # Threshold 0.5 지정
pred_y

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])