# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(13,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(il, ol)
model.compile(loss='mse', optimizer='adam')

In [6]:
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 3ms/step - loss: 146969.9062
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 135985.1406
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 125604.3906
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 115838.8203
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 106554.0312
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 97961.1641
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 89899.7812
Epoch 8/10
16/16 [==============================] - 0s 1ms/step - loss: 82340.7812
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 75325.8750
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 68781.8906


In [10]:
print(model.predict(x[:10]).reshape(-1))
print(y[:10])

[-236.48192 -219.54805 -218.10321 -217.17757 -217.74968 -217.17986
 -232.79507 -232.46986 -224.10944 -227.80002]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]


# Logistic Regression 쬐금 더 어려운 데이터

In [11]:
from sklearn.datasets import load_breast_cancer

In [12]:
cancer = load_breast_cancer()

In [13]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [14]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(il, ol)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

In [15]:
model.fit(x, y, epochs=10)

Epoch 1/10
18/18 [==============================] - 1s 3ms/step - loss: 110.6621 - accuracy: 0.3726
Epoch 2/10
18/18 [==============================] - 0s 3ms/step - loss: 96.2329 - accuracy: 0.3726
Epoch 3/10
18/18 [==============================] - 0s 2ms/step - loss: 81.9294 - accuracy: 0.3726
Epoch 4/10
18/18 [==============================] - 0s 3ms/step - loss: 67.6298 - accuracy: 0.3726
Epoch 5/10
18/18 [==============================] - 0s 3ms/step - loss: 53.1906 - accuracy: 0.3726
Epoch 6/10
18/18 [==============================] - 0s 3ms/step - loss: 39.0696 - accuracy: 0.3726
Epoch 7/10
18/18 [==============================] - 0s 3ms/step - loss: 24.8394 - accuracy: 0.3937
Epoch 8/10
18/18 [==============================] - 0s 4ms/step - loss: 11.5747 - accuracy: 0.4974
Epoch 9/10
18/18 [==============================] - 0s 3ms/step - loss: 2.9767 - accuracy: 0.7311
Epoch 10/10
18/18 [==============================] - 0s 3ms/step - loss: 1.0730 - accuracy: 0.8805


In [16]:
y_pred = model.predict(x).reshape(-1)
y_pred = np.where(y_pred>.5, 1, 0)
print(y_pred[:10])
print(y[:10])

[0 0 0 1 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0]
