# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris = load_iris()

In [18]:
x = iris.data
y = iris.target

In [19]:
x.shape, y.shape

((150, 4), (150,))

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = .2, random_state=2022)

In [21]:
#####################
# 라이브러리 불러오기
#####################
import numpy as np
import tensorflow as tf
from tensorflow import keras

- 전처리 시 train-test 분리 후 one-hot encoding 진행

In [22]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################
class_n = len(np.unique(y_train))

y_train = keras.utils.to_categorical(y_train, class_n)

In [23]:
########
# 모델링
########
keras.backend.clear_session()

model = keras.models.Sequential()
model.add(keras.layers.Dense(3, input_shape=(4,), activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='accuracy')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [24]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
4/4 [==============================] - 0s 4ms/step - loss: 1.9774 - accuracy: 0.1083
Epoch 2/10
4/4 [==============================] - 0s 3ms/step - loss: 1.9544 - accuracy: 0.1250
Epoch 3/10
4/4 [==============================] - 0s 3ms/step - loss: 1.9299 - accuracy: 0.1250
Epoch 4/10
4/4 [==============================] - 0s 3ms/step - loss: 1.9058 - accuracy: 0.1250
Epoch 5/10
4/4 [==============================] - 0s 3ms/step - loss: 1.8823 - accuracy: 0.1250
Epoch 6/10
4/4 [==============================] - 0s 3ms/step - loss: 1.8607 - accuracy: 0.1333
Epoch 7/10
4/4 [==============================] - 0s 2ms/step - loss: 1.8369 - accuracy: 0.1333
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 1.8164 - accuracy: 0.1333
Epoch 9/10
4/4 [==============================] - 0s 3ms/step - loss: 1.7957 - accuracy: 0.1333
Epoch 10/10
4/4 [==============================] - 0s 3ms/step - loss: 1.7762 - accuracy: 0.1333


In [25]:
###########
# 모델 예측
###########
y_pred = model.predict(x_train)
print(y_pred[:10].argmax(axis=1))
print(y_test[:10])

[2 2 1 2 2 2 2 2 2 2]
[2 2 0 2 0 0 1 1 0 1]


# 히든 레이어 추가하여 모델링! (Functional API)

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [28]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape=(4,), name='Input')
h1 = keras.layers.Dense(32, activation='relu', name='Hidden_1')(il)
h2 = keras.layers.Dense(32, activation='relu', name='Hidden_2')(h1)
ol = keras.layers.Dense(3, activation='softmax', name='Output')(h2)

model = keras.models.Model(il, ol)

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics='accuracy')

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 Input (InputLayer)          [(None, 4)]               0         
                                                                 
 Hidden_1 (Dense)            (None, 32)                160       
                                                                 
 Hidden_2 (Dense)            (None, 32)                1056      
                                                                 
 Output (Dense)              (None, 3)                 99        
                                                                 
Total params: 1,315
Trainable params: 1,315
Non-trainable params: 0
_________________________________________________________________


In [29]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
4/4 [==============================] - 0s 4ms/step - loss: 1.4415 - accuracy: 0.3500
Epoch 2/10
4/4 [==============================] - 0s 4ms/step - loss: 1.2623 - accuracy: 0.3500
Epoch 3/10
4/4 [==============================] - 0s 3ms/step - loss: 1.1297 - accuracy: 0.3500
Epoch 4/10
4/4 [==============================] - 0s 4ms/step - loss: 1.0396 - accuracy: 0.3750
Epoch 5/10
4/4 [==============================] - 0s 6ms/step - loss: 0.9705 - accuracy: 0.5917
Epoch 6/10
4/4 [==============================] - 0s 5ms/step - loss: 0.9301 - accuracy: 0.6667
Epoch 7/10
4/4 [==============================] - 0s 3ms/step - loss: 0.8964 - accuracy: 0.7167
Epoch 8/10
4/4 [==============================] - 0s 3ms/step - loss: 0.8615 - accuracy: 0.8000
Epoch 9/10
4/4 [==============================] - 0s 4ms/step - loss: 0.8275 - accuracy: 0.8000
Epoch 10/10
4/4 [==============================] - 0s 4ms/step - loss: 0.7949 - accuracy: 0.8000


In [30]:
###########
# 모델 예측
###########
y_pred = model.predict(x_train)
print(y_pred[:10].argmax(axis=1))
print(y_test[:10])

[0 1 1 0 1 0 0 1 0 2]
[2 2 0 2 0 0 1 1 0 1]
