# Keras로 Linear&Logistic Regression 맛보기!

#### 실습목표<br>
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [2]:
x = np.array(range(0,20)) 
y = x * 2 -1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss = 'mse', optimizer = 'adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

In [ ]:
# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [3]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [4]:
x = np.array(range(0,20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [5]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1)(il)

model = keras.models.Model(inputs=il, outputs=ol)
model.compile(loss='mse', optimizer='adam')

In [7]:
model.fit(x, y, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 10ms/step - loss: 672.9681
Epoch 2/10
1/1 [==============================] - 0s 12ms/step - loss: 672.3652
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 671.7627
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 671.1605
Epoch 5/10
1/1 [==============================] - 0s 6ms/step - loss: 670.5585
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 669.9569
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 669.3556
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 668.7547
Epoch 9/10
1/1 [==============================] - 0s 5ms/step - loss: 668.1540
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 667.5536


In [8]:
print(y)
print(model.predict(x).reshape(-1,) )

[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]
[-0.01099764  0.03546968  0.08193701  0.12840433  0.17487167  0.221339
  0.2678063   0.31427363  0.36074096  0.4072083   0.45367563  0.50014293
  0.54661024  0.5930776   0.6395449   0.68601227  0.7324796   0.7789469
  0.82541424  0.87188154]


## Quick Logistic Regression!

In [15]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [16]:
x = np.array(range(0,20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [17]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer) # inputs, outputs를 명시할 경우 구버전에서 에러 발생하기도 함 -> 순서만 맞춰서 파라미터 삽입


# 컴파일 해주렴
model.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [18]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

Epoch 1/10
1/1 [==============================] - 0s 408ms/step - loss: 11.9014 - accuracy: 0.5000
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 11.8937 - accuracy: 0.4500
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 11.8860 - accuracy: 0.4500
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 11.8783 - accuracy: 0.4500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 11.8706 - accuracy: 0.4500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 11.8629 - accuracy: 0.4500
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 11.8552 - accuracy: 0.4500
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 11.8475 - accuracy: 0.4500
Epoch 9/10
1/1 [==============================] - 0s 10ms/step - loss: 11.8398 - accuracy: 0.4500
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 11.8321 - accuracy: 0.4500
[0 0 0 0 0 0 0 0 0 0 1 1 1

## Now, Your turn!

In [10]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [11]:
x = np.array(range(0,40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [12]:
keras.backend.clear_session()

il = keras.layers.Input(shape=(1,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(inputs=il, outputs=ol)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
model.fit(x, y, epochs=10)

Epoch 1/10
2/2 [==============================] - 0s 8ms/step - loss: 1.1561 - accuracy: 0.5000
Epoch 2/10
2/2 [==============================] - 0s 7ms/step - loss: 1.1352 - accuracy: 0.4750
Epoch 3/10
2/2 [==============================] - 0s 7ms/step - loss: 1.1127 - accuracy: 0.4750
Epoch 4/10
2/2 [==============================] - 0s 6ms/step - loss: 1.0918 - accuracy: 0.4750
Epoch 5/10
2/2 [==============================] - 0s 9ms/step - loss: 1.0699 - accuracy: 0.4750
Epoch 6/10
2/2 [==============================] - 0s 7ms/step - loss: 1.0510 - accuracy: 0.4750
Epoch 7/10
2/2 [==============================] - 0s 5ms/step - loss: 1.0309 - accuracy: 0.4750
Epoch 8/10
2/2 [==============================] - 0s 7ms/step - loss: 1.0113 - accuracy: 0.4750
Epoch 9/10
2/2 [==============================] - 0s 5ms/step - loss: 0.9922 - accuracy: 0.4750
Epoch 10/10
2/2 [==============================] - 0s 4ms/step - loss: 0.9724 - accuracy: 0.4750


In [14]:
print(y)
print(model.predict(x).reshape(-1,) )

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
[0.5043943  0.4951849  0.48597878 0.47678214 0.46760124 0.4584422
 0.44931117 0.4402142  0.43115717 0.42214596 0.4131863  0.40428376
 0.39544377 0.3866716  0.3779724  0.36935103 0.3608122  0.35236055
 0.34400025 0.33573556 0.32757023 0.31950796 0.3115522  0.30370617
 0.2959727  0.2883547  0.28085446 0.2734744  0.26621646 0.25908244
 0.25207394 0.24519226 0.23843858 0.23181379 0.22531861 0.21895358
 0.21271893 0.20661485 0.20064133 0.19479808]
