# Keras로 Linear&Logistic Regression 조금 더 맛보기

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

# Linear Regression on 쬐금 더 어려운 데이터

In [2]:
from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [4]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [5]:
keras.backend.clear_session()

model = keras.models.Sequential()
model.add(keras.layers.Dense(1, input_shape=(13,))) # activation = 'linear'(default)
model.compile(loss='mse', optimizer='adam')

In [6]:
model.fit(x, y, epochs=10)

Epoch 1/10
16/16 [==============================] - 1s 2ms/step - loss: 150898.4219
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 139737.8438
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 129085.9609
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 119164.9766
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 109733.7734
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 100950.8672
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 92686.1641
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 84899.2812
Epoch 9/10
16/16 [==============================] - 0s 2ms/step - loss: 77750.6953
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 71001.3516


In [8]:
pred_y = model.predict(x).reshape(-1)
print(pred_y[:10])
print(y[:10])

[263.74252 233.32365 239.07227 243.83714 240.99586 237.24345 267.09512
 253.22404 251.36392 253.52876]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9]


# Logistic Regression 쬐금 더 어려운 데이터

In [9]:
from sklearn.datasets import load_breast_cancer

In [10]:
cancer = load_breast_cancer()

In [11]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape, y.shape

((569, 30), (569,))

In [12]:
keras.backend.clear_session()

model = keras.models.Sequential()
model.add(keras.layers.Dense(1, input_shape=(30,), activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=keras.metrics.BinaryAccuracy())

In [14]:
model.fit(x, y, epochs=10)

Epoch 1/10
18/18 [==============================] - 0s 2ms/step - loss: 30.3335 - binary_accuracy: 0.1353
Epoch 2/10
18/18 [==============================] - 0s 3ms/step - loss: 29.1221 - binary_accuracy: 0.1424
Epoch 3/10
18/18 [==============================] - 0s 3ms/step - loss: 28.0075 - binary_accuracy: 0.1441
Epoch 4/10
18/18 [==============================] - 0s 3ms/step - loss: 26.8104 - binary_accuracy: 0.1529
Epoch 5/10
18/18 [==============================] - 0s 4ms/step - loss: 25.6318 - binary_accuracy: 0.1564
Epoch 6/10
18/18 [==============================] - 0s 6ms/step - loss: 24.4634 - binary_accuracy: 0.1670
Epoch 7/10
18/18 [==============================] - 0s 4ms/step - loss: 23.2627 - binary_accuracy: 0.1757
Epoch 8/10
18/18 [==============================] - 0s 5ms/step - loss: 22.1606 - binary_accuracy: 0.1898
Epoch 9/10
18/18 [==============================] - 0s 3ms/step - loss: 21.0368 - binary_accuracy: 0.1986
Epoch 10/10
18/18 [===========================

In [15]:
pred_y = model.predict(x).reshape(-1)
pred_y = np.where(pred_y > 0.5, 1, 0)

print(pred_y[:10])
print(y[:10])

[1 1 1 1 0 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
