# 1일차 Review : 같은 문제 다시 풀어보기

    학습은 10번으로!

In [ ]:
from sklearn.datasets import load_breast_cancer

In [ ]:
cancer = load_breast_cancer()

In [ ]:
x = cancer.data
y = cancer.target

In [ ]:
x.shape, y.shape

((569, 30), (569,))

In [ ]:
# train / test set 분리
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=.2, random_state=2022)

In [ ]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

In [ ]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
ol = keras.layers.Dense(1, activation='sigmoid')(il)

model = keras.models.Model(il, ol)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 86.7168 - accuracy: 0.3648
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 74.5927 - accuracy: 0.3648
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 62.4497 - accuracy: 0.3648
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 50.1707 - accuracy: 0.3648
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 38.0944 - accuracy: 0.3648
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 25.9930 - accuracy: 0.3780
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 14.5711 - accuracy: 0.4396
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 5.6407 - accuracy: 0.6418
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 1.5883 - accuracy: 0.8549
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.8732 - accuracy: 0.9165


In [ ]:
###########
# 모델 예측
###########
import numpy as np

pred_y = model.predict(x_test).reshape(-1)
pred_y = np.where(pred_y >= 0.5, 1, 0)
print(pred_y[:10])
print(y_test[:10])

[1 1 1 1 1 1 0 0 0 0]
[1 1 0 1 1 1 1 0 0 0]


# 히든 레이어 추가하여 모델링!

    히든 레이어 2개를 추가하여 다시 모델링!
    히든 레이어 노드 수 : 32
    히든 레이어 activation = 'relu'

In [ ]:
########
# 모델링
########
keras.backend.clear_session()

il = keras.layers.Input(shape=(30,))
d1 = keras.layers.Dense(32, activation = 'relu')(il)
d2 = keras.layers.Dense(32, activation = 'relu')(d1)
ol = keras.layers.Dense(1, activation='sigmoid')(d2)

model = keras.models.Model(il, ol)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics='accuracy')

model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [ ]:
###########
# 모델 학습
###########
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
15/15 [==============================] - 1s 3ms/step - loss: 4.7354 - accuracy: 0.5978
Epoch 2/10
15/15 [==============================] - 0s 3ms/step - loss: 1.0066 - accuracy: 0.7033
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3704 - accuracy: 0.8440
Epoch 4/10
15/15 [==============================] - 0s 3ms/step - loss: 0.3366 - accuracy: 0.8791
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3275 - accuracy: 0.8703
Epoch 6/10
15/15 [==============================] - 0s 4ms/step - loss: 0.2694 - accuracy: 0.9055
Epoch 7/10
15/15 [==============================] - 0s 5ms/step - loss: 0.2560 - accuracy: 0.9077
Epoch 8/10
15/15 [==============================] - 0s 3ms/step - loss: 0.2562 - accuracy: 0.9011
Epoch 9/10
15/15 [==============================] - 0s 3ms/step - loss: 0.2566 - accuracy: 0.8901
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2732 - accuracy: 0.8835


In [ ]:
###########
# 모델 예측
###########
pred_y = model.predict(x_test).reshape(-1)
pred_y = np.where(pred_y >= 0.5, 1, 0)
print(pred_y[:10])
print(y_test[:10])

[1 1 1 1 1 1 0 0 0 0]
[1 1 0 1 1 1 1 0 0 0]
